spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//${DB_HOST:localhost}:${DB_PORT:1521}/${DB_NAME:XEPDB1}
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      minimumIdle: 5
      maximum-pool-size: 5
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: HikariPoolBooks
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true
