spring.profiles.active=test

spring.application.name=document-mngr

spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true


addressbook.api.url=http://localhost:8181/api

open.api.spec.url=https://veeteq.github.io/OpenAPI-DocumentMngr/openapi.yaml
#open.api.spec.url=http://localhost:8181/openapi.json

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.zalando.logbook.Logbook=TRACE