spring.profiles.active=test

spring.application.name=document-mngr

spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

# Hibernate ddl auto (create, create-drop, validate, update)

addressbook.api.url=http://localhost:8181/api
