#openapi.inputSpec=http://127.0.0.1:4000/_bundle/openapi/openapi.yaml
openapi.inputSpec=https://veeteq.github.io/OpenAPI-DocumentMngr/openapi.yaml
#openapi.inputSpec=${project.basedir}/src/main/resources/openapi.yaml